# Generated by Django 4.0.3 on 2022-04-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_registromascota_enfermedades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromascota',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
