# Generated by Django 4.0.3 on 2022-04-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_registromascota_imagen_registromascota_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registromascota',
            old_name='image',
            new_name='imagen',
        ),
    ]
