# Generated by Django 4.0.3 on 2022-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_image_registromascota_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromascota',
            name='nombre',
        ),
        migrations.AddField(
            model_name='registromascota',
            name='id_unica',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
