# Generated by Django 4.0.3 on 2022-04-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_registromascota_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromascota',
            name='nombre',
            field=models.CharField(default='perrito', max_length=50),
            preserve_default=False,
        ),
    ]
