# Generated by Django 4.0.3 on 2022-04-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_registromascota_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromascota',
            name='id_unica',
        ),
    ]
