# Generated by Django 4.0.3 on 2022-04-19 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_registromascota_id_unica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromascota',
            name='fecha_de_rescate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
