# Generated by Django 4.0.3 on 2022-04-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_registromascota_fecha_de_rescate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromascota',
            name='fecha_de_rescate',
            field=models.DateTimeField(),
        ),
    ]
