# Generated by Django 4.0.3 on 2022-04-19 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_registromascota_fecha_de_rescate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=8)),
                ('Domicilio', models.CharField(max_length=100)),
                ('NumeroMasc', models.IntegerField()),
                ('Razones', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='registromascota',
            name='fecha_de_rescate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
