# Generated by Django 4.0.3 on 2022-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_solicitudadop_alter_registromascota_fecha_de_rescate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudadop',
            name='Apellidos',
        ),
        migrations.AddField(
            model_name='registromascota',
            name='adoptante',
            field=models.CharField(default='Disponible', max_length=100),
            preserve_default=False,
        ),
    ]
