# Generated by Django 4.0.3 on 2022-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_solicitudadop_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='mamahuevo', max_length=50),
            preserve_default=False,
        ),
    ]
