# Generated by Django 4.0.3 on 2022-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromascota',
            name='adoptante',
            field=models.CharField(default='Disponible', max_length=50),
        ),
    ]
