# Generated by Django 4.0.3 on 2022-04-21 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_registromascota_adoptante'),
    ]

    operations = [
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimentacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.registromascota')),
            ],
        ),
    ]
