# Generated by Django 4.0.3 on 2022-04-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_comida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comida',
        ),
    ]
