# Generated by Django 4.0.3 on 2022-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadop',
            name='Aprobado',
            field=models.BooleanField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
