# Generated by Django 4.0.3 on 2022-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_solicitudadop_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadop',
            name='Aprobado',
            field=models.CharField(max_length=15),
        ),
    ]
