# Generated by Django 4.0.3 on 2022-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_solicitudadop_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadop',
            name='Aprobado',
            field=models.CharField(default='En proceso', max_length=15),
        ),
    ]
